### ISSUE TITLE
Glossary for guidance

### ISSUE THREAD

**Issue by wwqrd** [codaco/Architect#155]
We have a lot of specific language in Network Canvas that will probably be used throughout the guidance section to anchor concepts together, as well as academic language which we may want to explicitly connect to those concepts. For example,

> These properties can be added to **nodes** using the various **interfaces.**

Might it be worth putting a glossary directly into the app?

**Comment by jthrilly** [comment]
I'm really glad to see you thinking about this from a user-centric perspective. You're right that the language we use is very technical and subject specific, and this could be an issue.

My current thinking on the matter is as follows:

- Our users should be considered to be knowledgable regarding fundamental network terminology (nodes, edges, properties, sociograms, name generators, etc.), and of general statistical/survey terminology (ordinal scales, variables, etc.).
- We plan to introduce users to the new network canvas vocabulary through specific trainings and workshops, since some new language is unavoidable. Thinking here about how apps like Excel required words such a "sheets", which are analogous to our "interfaces" and "stages".
- However, for this to work we must take care to be 100% consistent in our use of terminology, and so our team must be confident in its use. Additionally, significant numbers of users will be attempting to pick up the software without any form of training.
- Given the above, I think it would be prudent to develop/refine the wiki page we have for definitions (https://github.com/codaco/Network-Canvas/wiki/Definitions) with aim of ultimately directing users here. Rename it to "Glossary", and put it in a table perhaps? Suggestions welcome.

**Comment by wwqrd** [comment]
How about we add hyperlinks from the guidance section to the wiki for the keywords?

**Comment by jthrilly** [comment]
Good suggestion. Any thoughts on how to organize the wiki page for the definitions?

**Comment by jthrilly** [comment]
The glossary itself is being worked on by @berniehogan. We should look to integrate it with hyperlinks when it is part of the new documentation website.

**Comment by jthrilly** [comment]
Guidance has been removed for the time being, and can be reinstated in the future.
