### ISSUE TITLE
General UI

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#2]
A blank space where UI discussion will happen.

**Comment by berniehogan** [comment]
Much like wireframing apps, should we have cords that link stages to indicate piping?

**Comment by jthrilly** [comment]
> Much like wireframing apps, should we have cords that link stages to indicate piping?
Interesting idea. Is that where you see the skip logic happening? We don't currently support alternate paths (branching style) - just skipping. Seems like we could do something like:

```
 ---         ---
|   |--( )--|   |
 ---         ---
```

Where the cards represent the stages, and the circle represents the skip logic.

**Comment by berniehogan** [comment]
I'm not sure that the visual display of the skip logic will be the most important. Consistency and navigability will be key. I think having an afford for [SKIP LOGIC] in  the upper corner of a given stage would be sufficient. A mouse over might say:
[This question depends on the results of STAGE 2]

with a click to edit. I don't deny it is cool, but I don't think it is necessary, either. 

I see the attraction of the cords, like in wireframing software, but I think the qualtrics / survey monkey approach would be sufficient. Further, I think that worrying about the front end rather than the workflow is not in the right order. Give me a basic control for selecting question piping first, and then later we can think about how to make it look nice by talking to / watching users.

**Comment by jthrilly** [comment]
I've actually already mocked this up interactively. I will be sharing the prototype shortly. I'd be interested in perhaps presenting some of these prototypes and using them to refine the design.
