### ISSUE TITLE
Editing a variable after it has been added to a form can create invalid states

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#208]
If I edit the nickname variable (say by renaming it to "display name"), it seems to update correctly in the "add a new person" form, but in Network Canvas the form displays without a label. 

Removing the variable from the form and adding it again corrects this issue.

**Comment by wwqrd** [comment]
@jthrilly What do you think the expected behaviour should be?

Because the name is also the 'id', changing it breaks all the references throughout the app: it appears to keep the reference in the form editor but the actual protocol still holds the old value.

At the moment it would be relatively straightforward to auto update references, but that could be brittle long term as more parts of the protocol depend on the reference.

Another option would be to reconsider how this is stored in the protocol. Perhaps separating out the variable name from the id. That would then either need changes in network canvas when we attach these properties to nodes, or the export function could handle references (probably preferable).

**Comment by jthrilly** [comment]
How about using a UID as the reference, and relegating name to a property?
