### ISSUE TITLE
Missing "operator" in filter when the rule type is edge

### ISSUE THREAD

**Issue by bryfox** [codaco/Architect#255]
When configuring a NameGenerator panel, if I add an *edge* filter, I am prompted to choose the option type, but not the operator.

```
            "rules": [
              {
                "type": "edge",
                "id": "15391306412403",
                "options": {
                  "type": "aecba335e84ca9e3a2b7990230dcf248e6826e42"
                }
              }
            ]
```

[`operator` is documented as required](https://github.com/codaco/Network-Canvas/wiki/Skip-Logic#skip-logic-api); presumably the user can choose 'exists' or 'not_exists'.

We should either choose a default for `operator` (in documentation, and NC if needed), or allow the user to edit operator and add a default here.

**Comment by wwqrd** [comment]
Currently edge rules require that we specify an attribute, but don't allow us to specify a value. Additionally, alter rules require that we specify an attribute and a value. Both rule types should allow us to either specify:

a) `EXISTS` / `NOT_EXISTS` on edge/alter type, these operators don't require a value.
b) `EXACTLY`, `NOT, GREATER_THAN`, `GREATER_THAN_OR_EQUAL`, `LESS_THAN`, `LESS_THAN_OR_EQUAL` on entity attributes, and require a value.

**Comment by wwqrd** [comment]
No problem! I understood what you meant - it's a bug for sure.

My comment was just to include a bit more detail on how this deviates from the intended behaviour. The issue is broader than the UI bug, because it impacts networkQuery functions too.

RE: `EXISTS`/`NOT_EXISTS`, we do actually want to allow `NOT_EXISTS`. The query library is node-centric, so to filter a `{ network }` by edge `NOT_EXISTS` means to return all nodes that didn't have that edge type connected to them (and indirectly, all edges connected to those nodes).
