### ISSUE TITLE
Ability to create a new variable from the "additional attributes" section of the name generator prompt config

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#293]
A user should be able to create a new variable from the additional attributes section of the name generator prompt configuration.

**Comment by wwqrd** [comment]
In order to make this manageable long term, I think it would be best to introduce some UI state into redux.

Reasoning:
  - current approach for top-level views relies on routing to show one view per route, means that we can't "stack" screens, navigating to/from a screen loses all previous state of that screen
  - in places we have been able to include screens nested within one another so that a 'parent' screen can manage the state of 'linked to' screens. Expanding this approach would require adding the component to every other component that needed to open the 'sub-screen', which might even introduce circular dependencies
  - current approach doesn't give a clear path for breadcrumbs. History is kept in the dom history object which is write-only (this actually causes problems for page refresh too, where we can't go "back" to the start screen)

Planned approach:
  - add a ui state to redux which is persisted with redux-persist (already in use)
    state might look something like this:
    ```js
    {
      ui: {
        root: 'start',
        screens: [
          // order denotes stacking
          {
            screen: 'edit-stage',
            payload: { /* edit stage specific ui options */ },
          },
          {
            screen: 'codebook'
            payload: { /* codebook specific ui options */ },
          }
        ],
      }
      ...
    }
    ```
  - The <Cards /> component which is half-way there to supporting this kind of feature, will be updated to <Screens /> and use the ui state to determine rendering.
 
Advantages:
  - By dispatching an action a screen can be opened from anywhere in the app
  - We will have a clear hierarchy/history of open screens, allowing us to render breadcrumbs or otherwise alter the views to indicate nested navigation.
  - Since multiple screens may be open at once, react state can be maintained when returning to a parent screen.
 
Challenges:
   - When creating an entity for use on a parent screen, we would often also like to automatically use that new entity automatically - how can we inform the parent screen?
