### ISSUE TITLE
Add content button disappears on "Edit information screen"

### ISSUE THREAD

**Issue by berniehogan** [codaco/Architect#316]
Select new stage: information screen. 
Add new content, type "Text"
Select Display size "Large"
Add more content button disappears, select medium it reappears. 

Alpha 8, reproduced on mac and windows.

**Comment by jthrilly** [comment]
I think I see what has happened here - this one is actually "by design". The idea of the display sizes is that you have a certain "budget" for content that will fit on the screen, which you can choose to spend using any combination of content boxes, with each size taking up a proportionally greater amount. So say you had 8 screen units budget, a large box size takes up 8, a medium takes up 4, and a small takes up 2. 

The current behaviour is really confusing though, so I will add some explanation of this system to the guidance and the inline description of that area. I will also add a message saying that there is no space for additional items, rather than moving the add button entirely.

We did this because we wanted to avoid having overflowing information screens that users would need to scroll. It seemed to break some of the spatial consistency of the design to have a full page scrolling layout, set inside a vertically scrolling timeline. If you think scrolling would be preferable, we can look at a different design.
