### ISSUE TITLE
Set color for input error text

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#370]
There is a new style for input error display (validation, such as "required", or "maxSelected"). The text is currently displayed using dark text in Architect. This should be updated to use white text so that it is visible.

**Comment by jthrilly** [comment]
@wwqrd - has this been resolved by you in #375?

**Comment by wwqrd** [comment]
Possibly not. The issue mentioned in #375 was due to TextArea (in UI), there's a PR for that here: https://github.com/codaco/Network-Canvas-UI/pull/96. However the error color is used in a few other places in Architect, so if those have changed it may still be an issue generally. Suggest we leave this open for now until that gets checked out.
