### ISSUE TITLE
Variables should only be assigned once per interview. (Refactor variable definition)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#392]
To mirror the way that variable use works in other survey software, we want to move to a system where a variable can only be used/assigned once per protocol. Once a variable has been used in this way, it will no longer appear inside the dropdown of available variables in an interface configuration screen, form creation screen, or elsewhere.

**Comment by wwqrd** [comment]
This is interesting, one thing that concerns me about features like this is keeping an updated manifest of where variables might be found. If we keep an accurate record today but then later allow variables to be used in a new kind of interface this list could get left behind. There are similar issues with checking for unused variables.

What would make this easier to manage would be to keep an index of which variables are used where. This disadvantage of that being some duplication, and it would make it harder to create a protocol manually.

**Comment by rebeccamadsen** [comment]
Huh. So, I could see this eliminating some user errors, in that users wouldn't unintentionally re-use the same variable in different context, potentially overwriting data during an interview. However, it also imposes some constraints. So one scenario might be that the user uses skip logic to determine which interface to show, but both possible interfaces share a variable. That wouldn't be possible with this constraint. Would that also mean that if the user uses two name generator interfaces that they can't both use the same variable for name? I suppose that encourages the use of prompts instead of an additional interface?

I'm guessing with this constraint it just means the user may have variables that are related to some degree, and they have to use some logic to connect them in whatever evaluation tool they choose.

**Comment by wwqrd** [comment]
I think one usage per asset might be the right thing to do for the asset manifest too. Having an abstracted library of assets isn't necessarily useful to the user. When thinking about building the asset library:
- If an asset is used in more that one place, how do we explain that to the user?
- If an asset is updated in the library (which would automatically update an interface), is that useful? The user would need have a mental model of the context of where assets are used. It may make more sense to simply link the user to the relevant interface, from which the field can be managed en situ.

**Comment by wwqrd** [comment]
@rebeccamadsen My interpretation is that this applies to places where variables are written to only, such as prompts and forms. Otherwise we won't even be able to use `name` attribute to label or sort nodes/cards on each interface.
