### ISSUE TITLE
variable with no type

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Architect#539]
In form fields, if you type a variable name and press enter, but change your mind and create a different name or select an existing variable, and continue, you can end up with a variable with no type that isn't being used anywhere. This causes a protocol-validation error on save (the first of the two errors in this example).

![notype](https://user-images.githubusercontent.com/16093053/59357175-5b1e4800-8cf8-11e9-9290-2242258a1ec4.png)

**Comment by wwqrd** [comment]
I think your suggestion @rebeccamadsen  of drafting the variables until the user saves the field is the right approach here.

I had been inclined to tidy up afterwards so it could continue to use the inline CREATE_VARIABLE action, but I think that is the actually the root mistake!

I might also add some checking in the codebook module so that type is a required property.

- Instead of creating a variable in the selector, add the name to state.
- Create/update the variable when the field is saved
- Update codebook module to require variable type
