### ISSUE TITLE
Field Input Control cannot be changed after initial selection

### ISSUE THREAD

**Issue by marioangst** [codaco/Architect#550]
When choosing the input control for a field, after an initial selection (eg. Number), the input control cannot be changed again (other options are not displayed anymore).

Beta Version v4.0.1 (I think).

See below for an example

![inputform](https://user-images.githubusercontent.com/19803038/59752710-0a23cc00-9283-11e9-91ad-6a59c88caa66.PNG)

**Comment by wwqrd** [comment]
This is the result of a 'convinience' feature: the input control is used to determine the variable type.

...and once the variable type has been set it's immutable. Input controls that don't match the type are hidden, and many of the types only have one appropriate input control.

From a user perspective I don't think its clear at all that's what's going on!

A couple of ideas for improving this:
- The first time a field (variable) is created, allow the input control (type), to be changed until the field is saved. After editing it'll become immutable again, but this is by design so that other interfaces don't get broken by changes.
- Display the variable type that is being automatically set somewhere? Might add more confusion if it can't be changed directly?

**Comment by jthrilly** [comment]
> * The first time a field (variable) is created, allow the input control (type), to be changed until the field is saved. After editing it'll become immutable again, but this is by design so that other interfaces don't get broken by changes.
> * Display the variable type that is being automatically set somewhere? Might add more confusion if it can't be changed directly?

I think both of these. The variable type can be shown as a hint below the input:
`This input component creates a **type** variable.`

One other thing that would help would be to add additional text when the input type is locked which explains why, and how to work around it (which is to create another variable)

**Comment by marioangst** [comment]
This looks like the perfect fix for it. Considering the suggestions made by @wwqrd I would say that the first point would have already addressed the issue for many users. Additional text if the input is locked would definitely help - it is much easier as a user to accept not being allowed to do something if it is explained to you why that is the case.
