### ISSUE TITLE
Don't show the delete cross next to variables that cannot be deleted

### ISSUE THREAD

**Issue by jthrilly** [codaco/Architect#572]
In the following screenshot, I used `discussFreq` elsewhere in the interview, so it cannot be deleted from this select dropdown. Clicking the 'X' does nothing.

<img width="1349" alt="Screen Shot 2019-08-23 at 11 07 21 AM" src="https://user-images.githubusercontent.com/1387940/63585118-4848af00-c596-11e9-9246-e9fe4ec824f3.png">

I think it would be better to:

1. Not show the cross when a variable can't be deleted
2. Show a small pill to let the user know a variable is unused (a pattern we use elsewhere, that we should make universal to showing a variable
3. Prompt to confirm deletion. Unsure about this one - perhaps not needed given the variable is unused.

Something like below:

<img width="1349" alt="Screen Shot 2019-08-23 at 11 12 48 AM" src="https://user-images.githubusercontent.com/1387940/63585418-f6545900-c596-11e9-8ec5-8896de2810f8.png">

**Comment by wwqrd** [comment]
I think this got cancelled before, because of complications with ophaned variables/assets.

This plan would seem fairly foolproof:
1. minimise intermediaries (ensure everything edits the 'live' protocol, not "drafts")
2. cancel button should 'revert' protocol to the point that that window was opened (we already have this capability).
3. assets should only be deleted on 'save' action (for the case that protocol reference changes are reverted)

**Comment by wwqrd** [comment]
## Update

I started an implementation based on the above but it proved too long winded (though promising).

- Refactoring the stage editor to edit the protocol live and in-place would be a Good Thing.
  - It would eliminate issues we have with desynchronised redux-form forms, which may be editing overlapping slices of protocol with different 'draft' states.
  - It will simplify the code because this inter-form communication would not need to happen.
  - Unfortunately, there is quite a lot of code to modify, because of aforementioned inter-form communation, so it's difficult to predict the time scales - however it seems obvious now that it isn't feasible for the time available until next release.

## Next

The primary aim of this feature is to make it easy to delete variables which have been accidentally created with incorrect details

### Options

#### If a new variable replaces a previous new variable, then "switch" them (automatically delete the other one).

- This is how form fields currently work, but they are quite different behind the scenes.
- Would not allow the deletion of *other* unused variables

#### Update the path variable usage check to include forms
- The existing approach for checking variable usage by paths is brittle, and had problems in the past so this isn't appealing.
  - Protocol changes that use variables will not automatically be reflected in the list of paths, so usage report will be inaccurate
  - The good thing about this approach is that is can include information about where a variable is used.

#### Create a simpler variable usage check (and include forms)
- A rough approch would be to stringify the state and look for the variable as a string
  - We do not need to keep a record of paths, so the protocol format can change without making
this defunct.
  - There won't be any information included about usage.
